{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.clusterexternalsecret" -}}
{{- $files := .Files }}
{{- $default_values := .Values.clusterexternalsecret_defaults }}
{{- $global_values := .Values.global}}
{{- $externalsecret_defaults := .Values.externalsecret_defaults }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .clusterexternalsecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ required "Name is required for ClusterExternalSecret" .name }}
spec:
  externalSecretName: {{ .name }}
  namespaces: {{- include "helpers.prefixNamespaces" (dict "namespaces" .namespaces "global" $global_values) | trim | nindent 4 }}
  refreshTime: {{ .refreshTime | default $default_values.refreshTime }}
  externalSecretSpec: 
    secretStoreRef:
      name: {{ .externalSecretSpec.secretStoreRef.name | default $global_values.cluster_secret_store.name }}
      kind: {{ .externalSecretSpec.secretStoreRef.kind | default $externalsecret_defaults.secretStoreRef.kind }}
    refreshInterval: {{ .externalSecretSpec.refreshInterval | default $externalsecret_defaults.refreshInterval }}
    target:
      name: {{ required "externalSecretSpec.target.name is required for ClusterExternalSecret" .externalSecretSpec.target.name }}
      creationPolicy: {{ .externalSecretSpec.target.creationPolicy | default $externalsecret_defaults.target.creationPolicy }}
    data:
    {{- range .externalSecretSpec.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ include "helpers.renderGlobalIfExists" (dict "value" (.remoteRef.key | default $global_values.cluster_secret_store.remoteRef.key) "global" $global_values) }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{- include "helpers.validateEnumValue" (list .remoteRef.decodingStrategy (list "Base64" "Base64URL" "Auto" "None")) }} {{ .remoteRef.decodingStrategy }}
        {{- end }}
        conversionStrategy: {{ .remoteRef.conversionStrategy | default $default_values.remoteRef.conversionStrategy }}
        metadataPolicy: {{ .remoteRef.metadataPolicy | default $default_values.remoteRef.metadataPolicy }}
    {{- end }}
    {{- if .externalSecretSpec.dataFrom }}
    dataFrom:
    {{- range .externalSecretSpec.dataFrom }}
      - key: {{ .key }}
      {{- if .version }}
      version: {{ .version }}
      {{- end }}
      {{- if .property }}
      property: {{ .property }}
      {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}