apiVersion: v2
name: chart-b
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: global-templates
    version: 1.0.0
    repository: https://xmcyber.github.io/helm-global-templates/
    import-values:
      - defaults # This is the default values file for the global-templates chart