apiVersion: v2
name: global-templates
description: A library chart that provides a set of reusable templates for Helm Charts
type: library
version: 1.3.0
dependencies:
  - name: common
    version: 2.6.0
    repository: https://charts.bitnami.com/bitnami
