microservice_defaults: &microservice_defaults
  serviceAccountName: default
  imagePullPolicy: IfNotPresent
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  nodeAffinityPreset:
    type: ""
  serviceAccount:
    create: false
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 5
    targetCPU: 80
    targetMemory: 80
    metrics: []
  resources:
    requests:
      cpu: 0.1
      memory: 0.5Gi

exports:
  defaults:
    common_defaults:
      labels: {}
      annotations: {}

    deployment_defaults: *microservice_defaults
      
    service_defaults:

    externalsecret_defaults:
      refreshInterval: "1h"
      secretStoreRef:
        kind: "Secret"
      target:
        creationPolicy: "Owner"
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None

    clusterexternalsecret_defaults:
      refreshTime: "1m"
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None

    scaledobjects_defaults:
      minReplicas: 1
      maxReplicas: 10
      pollingInterval: 30
      targetApiVersion: apps/v1
      targetKind: Deployment

    statefuleset_defaults: *microservice_defaults

    service_defaults:

    ingress_defaults:
      ingressClassName: ingress-nginx-internal
      path: '/'

    roles_defaults:
    rolebinding_defaults:
    serviceaccount_defaults:

    hpa_defaults:
      minReplicas: 3
      maxReplicas: 30
      targetApiVersion: apps/v1
      targetKind: Deployment
      targetCPUUtilizationPercentage: 60
